/**
 * `GasSwapper` — typed wrapper around the parent-chain GasSwapper
 * helper contract.
 *
 * The contract isn't deployed on every network; consumers that don't
 * need the swap-and-bridge entry point can simply not instantiate
 * this. Stage 4 audits whether the contract is still live and prunes
 * this class if not.
 */

import type { Hex, Adapter, PreparedTx, TxResult  } from '../adapter.js';
import type {ContractCallerOptions} from '../internal/contract-caller.js';
import type { Logger } from '../logger.js';

import { GasSwapperABI } from '../abi/index.js';
import { ContractCaller  } from '../internal/contract-caller.js';

export interface GasSwapperConfig {
  adapter: Adapter;
  getAddress: () => Promise<Hex>;
  logger: Logger;
  defaultFrom?: Hex;
}

export class GasSwapper {
  /**
   * @internal — wiring hook for POSClient's construction of the bridge
   * helpers. ContractCaller is not part of the public API contract and
   * may change shape in any release; consumers should treat this
   * member as non-existent.
   */
  readonly caller: ContractCaller;

  constructor(config: GasSwapperConfig) {
    this.caller = new ContractCaller({
      adapter: config.adapter,
      getAddress: config.getAddress,
      abi: GasSwapperABI,
      isParent: true,
      logger: config.logger,
      defaultFrom: config.defaultFrom
    });
  }

  /** Underlying caller — exposed for advanced consumers. */

  /**
   * Single-call deposit + ETH→token swap. Used by the `*WithGas`
   * variants on the token classes; consumers calling this directly
   * supply the full `swapCallData` (typically generated by an off-
   * chain quoter such as 0x or 1inch).
   */
  depositWithGas(
    tokenAddress: string,
    depositAmount: string,
    userAddress: string,
    swapCallData: string,
    options: ContractCallerOptions = {}
  ): Promise<TxResult> {
    return this.caller.write(
      'swapAndBridge',
      [tokenAddress, depositAmount, userAddress, swapCallData],
      options
    );
  }

  /** Same as {@link depositWithGas} but returns the unsigned `{ to, data, value? }`. */
  prepareDepositWithGas(
    tokenAddress: string,
    depositAmount: string,
    userAddress: string,
    swapCallData: string,
    options: ContractCallerOptions = {}
  ): Promise<PreparedTx> {
    return this.caller.prepareWrite(
      'swapAndBridge',
      [tokenAddress, depositAmount, userAddress, swapCallData],
      options
    );
  }
}
